### ISSUE TITLE
Résoudre les TODO

### ISSUE THREAD

**Issue by vhf** [zestedesavoir/zds-site#3897]
- [forum/models.py L32](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L32)
  - [x] `TODO: what is the usage of this function?`
- [forum/models.py L104](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L104)
  - [x] `# TODO: A forum defines an image, but it doesn't seems to be used...`
- [forum/models.py L214](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L214)
  - [x] `# TODO: 1. Use a better name, 2. maybe there can be a cleaner way to do this`
- [forum/models.py L258](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L258)
  - [x] `# TODO: Force relation with author here is strange. Probably linked with the`get_last_answer`function that`
- [forum/models.py L361](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L361)
  - [x] `# TODO: Why 2 nearly-identical functions? What is the functional need of these 2 things?`
- [forum/models.py L456](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L456)
  - [x] `# TODO: ça a l'air d'être OK en base, mais ne devrait-il pas y avoir une contrainte unique sur (topic, user) ?`
- [forum/models.py L470](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L470)
  - [x] `# TODO semble inutilisé (et peu efficace dans la manière de faire)`
- [forum/models.py L509](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/models.py#L509)
  - [x] `# TODO: voilà entre autres pourquoi il devrait y avoir une contrainte unique sur (topic, user) sur TopicRead.`
- [forum/tests/tests_feeds.py L282](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/tests/tests_feeds.py#L282)
  - [x] `# TODO : Fix this test, bug cause of markdown :(`
- [forum/views.py L643](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/views.py#L643)
  - [ ] `# TODO suggestions de recherche auto lors d'un nouveau topic, cf issues #99 et #580. Actuellement désactivées :(`
- [forum/views.py L648](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/forum/views.py#L648)
  - [x] `# TODO: WTF "sqs" ?!`
- [member/forms.py L327](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/forms.py#L327)
  - [ ] `# TODO: Updates the password --> requires a better name`
- [member/models.py L68](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L68)
  - [x] `# TODO: Change this name. This is a boolean: "true" is "hover" or "click" ?!`
- [member/models.py L76](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L76)
  - [ ] `# TODO: bad field name (singular --> should be plural), manually handled multi-valued field.`
- [member/models.py L331](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L331)
  - [x] `# TODO: improve this method's name?`
- [member/models.py L453](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L453)
  - [x] `# TODO: Seems unused`
- [member/models.py L505](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L505)
  - [x] `# TODO: coherence, "staff" is called "moderator" in Ban model.`
- [member/models.py L507](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L507)
  - [x] `# TODO: coherence, "comment" is called "text" in Ban model.`
- [member/models.py L510](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/models.py#L510)
  - [x] `# TODO: coherence, "create_at" is called "pubdate" in Ban model.`
- [member/tests/tests_models.py L268](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/tests/tests_models.py#L268)
  - [ ] `# TODO Some conditions still need to be tested`
- [member/tests/tests_models.py L275](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/tests/tests_models.py#L275)
  - [ ] `# TODO Some conditions still need to be tested`
- [member/views.py L59](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/member/views.py#L59)
  - [x] `# TODO When User will be no more used, you can make this request with`
- [tutorialv2/models/models_versioned.py L282](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/tutorialv2/models/models_versioned.py#L282)
  - [ ] `# TODO : path comparison instead of pure rewritring ?`
- [tutorialv2/views/views_validations.py L40](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/tutorialv2/views/views_validations.py#L40)
  - [ ] `# TODO: many filter at the same time ?`
- [tutorialv2/views/views_validations.py L41](https://github.com/zestedesavoir/zds-site/blob/7da461ca96090252972b9e4b6e379f400b3c5f45/zds/tutorialv2/views/views_validations.py#L41)
  - [ ] `# TODO: paginate ?`

**Comment by Anto59290** [comment]
Avec un ticket qu regroupe tous les Todo, faut-il s'attendre à une PR qui corrige de manière intégrale tous ces Todo ? (Ce qui serait la logique de ZdS). 

Le ticket #3064 aborde le même problème ;)

**Comment by vhf** [comment]
@Anto59290 De préférence une PR par TODO ou une PR par fichier. :)

L'idée est qu'une PR dit à quel ticket elle se réfère. Ici, une personne motivée peut commencer où elle veut, régler un TODO, référencer ce ticket dans sa PR. Puis continuer avec un autre TODO, etc. Au fur et à mesure que les TODOs seront traités, on pourra ici cocher la case : 
- [x] Donner un exemple de case

(Merci pour l'autre ticket, je l'ai fermé, celui-ci le remplace.)

**Comment by LudovicDrtt** [comment]
> forum/models.py L470
> 
> ```
> # TODO semble inutilisé (et peu efficace dans la manière de faire)
> ```

Cette fonction à effectivement l'air totalement inutilisée.

``` bash
# ludovic @ Tardis in /home/ludovic/workspace/Zds/zds-fork on git:modif x [13:54:08] C:2
$ grep -lrnwE '.' -e 'get_last_topics\([^)]'
(zdsenv) 
# ludovic @ Tardis in /home/ludovic/workspace/Zds/zds-fork on git:modif x [13:54:30] C:1
$ 
```

**PS** : la regex est là pour enlever la méthode get_last_topics qui est dans managers.py ln. 62

**Comment by LudovicDrtt** [comment]
> forum/models.py L361
> 
> ```
> # TODO: Why 2 nearly-identical functions? What is the functional need of these 2 things?
> ```

La première n'est absolument pas utilisé :

``` bash
# ludovic @ Tardis in /home/ludovic/workspace/Zds/zds-fork on git:todosolve x [14:40:17] C:130
$ grep -lrnw '.' -e 'resolve_first_post_url'
./doc/build/doctrees/back-end-code/forum.doctree
./doc/build/doctrees/environment.pickle
./doc/build/html/back-end-code/forum.html
./doc/build/html/genindex.html
./doc/build/html/searchindex.js
./zds/forum/models.py
```

Il y a que sa définition et la doc contrairement à la seconde :

``` bash
# ludovic @ Tardis in /home/ludovic/workspace/Zds/zds-fork on git:todosolve x [14:40:33] 
$ grep -lrnw '.' -e 'first_unread_post'
./templates/forum/base.html
./doc/build/doctrees/back-end-code/private-message.doctree
./doc/build/doctrees/back-end-code/forum.doctree
./doc/build/doctrees/environment.pickle
./doc/build/html/back-end-code/forum.html
./doc/build/html/back-end-code/private-message.html
./doc/build/html/genindex.html
./doc/build/html/searchindex.js
./zds/forum/models.py
./zds/forum/models.pyc
./zds/notification/management/commands/migrate_subscriptions.py
./zds/mp/models.py
./zds/mp/tests/tests_models.py
```

Du coup la question est : 

> Est-ce qu'on peut récupérer l'url à partir de l'objet en lui même ? 

Si oui `resolve_first_post_url` peut être supprimée. 

---

Et du coup pour get_last_topics, on la supprime ou j'essaye de la réécrire ?

**Comment by vhf** [comment]
> Est-ce qu'on peut récupérer l'url à partir de l'objet en lui même ?

Oui on peut. Avec l'objet et `reverse` ou un truc du genre.

Pour `get_last_topics` si c'est utilisé nulle part : viré.

**Comment by LudovicDrtt** [comment]
Ok je le vire je merge et on voit si ça passe les tests

**Comment by Anto59290** [comment]
Pour les deux dernier todo de la liste, il serait assez logique de s'en occuper en même temps que la Zep18. A noter que @artragis a déjà une PR visant à améliorer le front de la validation, qui couvre partielement la ZEP 18. Peut être peut-il faire d'une pierre deux coups ?

**Comment by Anto59290** [comment]
Le ticket #1722 est aussi un sous ticket de celui-ci. A noter que les Todo ne sont pas du tout explicites et que personne ne semble savoir quels tests sont manquants.

**Comment by vhf** [comment]
@Anto59290 et @LudoBike dans ce genre de cas, le rapport de coverage peut être utile. Ici on a deux commentaires dans 2 tests, ils disent qu'il faut encore tester une condition. [paf](https://coveralls.io/builds/8584164/source?filename=zds%2Fmember%2Fmodels.py#L337) :)

**Comment by Anto59290** [comment]
Bien vu ;)

**Comment by LudovicDrtt** [comment]
``` python
# TODO: WTF "sqs" ?!
sqs = SearchQuerySet().filter(content=AutoQuery(request.GET.get('q'))).order_by('-pubdate').all()
```

sqs -> SearchQuerySet 

Du coup je renomme la variable ou je supprime juste le todo

**Edit**: Non c'est vraiment un nom nul

**Comment by LudovicDrtt** [comment]
Du coup j'ai réfléchis un peu et j'ai trouvé ces noms
- similar_names
- similar_titles
- similarly_named
- similarly_entitled
- similar_posts

**Comment by vhf** [comment]
@LudoBike je dirais `similar_contents`. Tu veux bien en profiter pour renommer le compteur `cpt` en `counter` par exemple ? Ou autre, mais cohérent avec la codebase en anglais ?

**Comment by LudovicDrtt** [comment]
Ok pas de problème

**Comment by pierre-24** [comment]
Ok, grâce à @artragis, on avance :)

**Comment by gasche** [comment]
Il faudrait rajouter le label "Facile" sur cette issue car elle regroupe de nombreuses tâches dont certaines sont bonnes pour une première contribution.

**Comment by gllmc** [comment]
J'avais raté cette issue, mais le `# TODO: improve this method's name?` est fixé par #4089 :)

**Comment by pierre-24** [comment]
Merci :)

**Comment by AmarOk1412** [comment]
forum/views.py L643 fixée vu que ça a été enlevé
