### ISSUE TITLE
Migrer vers notre nouveau zmarkdown: Django

### ISSUE THREAD

**Issue by AmarOk1412** [zestedesavoir/zds-site#4388]
o/

https://github.com/zestedesavoir/zmarkdown avance bien. Et je pense qu'on peut commencer à regarder comment passer de la version Python à celle en JS.

Il y a pas mal de choses à voir, comme enlever Python-ZMarkdown, comment bien interfacer node et Django, etc.

Suggestions d'IRC :
+ Classique : une socket
+ http://www.grpc.io/docs/quickstart/node.html
+ https://channels.readthedocs.io/en/stable/
+ https://github.com/markfinger/python-js-host

---

## TODO côté zmd

- [x] Imbriquer > 235 citations donne une erreur Markdown #3878
- [x] Ne pas pinger dans les citations #4199

## TODO côté django

- ping:
  - [x] Voir un message où on est pingé donne une 500 #4192
  - [x] Ping et changement de nom d'utilisateur ? #4242
  - [x] Empêcher l'autoping #4198
  - [x] Editer un message pour enlever un ping devrait supprimer la subscription #4194
  - [x] Editer un message pingant reping. #4193
- [x] Remonter les erreurs de parsing zmd vers l'utilisateur (array `messages` dans la réponse)
- [x] Documentation du déploiement
- [x] Éviter de demander plusieurs fois le parsing de la même signature (ping @AmarOk1412)
- [x] Corriger le petit problème de mise à jour sur les forums et les publications (il faut éditer deux fois pour voir le texte se mettre à jour)
- [x] Enlever la requête vers l'api des membres pour pinger
- [x] les tutos moyens doivent être marqués `middle` et non `medium`
- [x] le cas du langage inconnu pour le code en md (ping @vhf en cours sur remark-rehype)

**Comment by vhf** [comment]
Merci pour ce ticket @AmarOk1412 . Je trouve pertinent, vu la quantité de travail et les directions diverses qu'on doit emprunter pour y arriver, de splitter ce ticket en 3.

1. Ce ticket concerne le backend/django/python/node<->django
1. Côté front-end https://github.com/zestedesavoir/zds-site/issues/4390
1. Côté PDF/LaTeX https://github.com/zestedesavoir/zds-site/issues/4391

**Comment by AmarOk1412** [comment]
Ouai, j'aurais soit fait ça, soit un méta ticket. Mais bon, c'est niquel la.

**Comment by artragis** [comment]
Nota : zerorpc nécessiterait gunicorn pour fonctionner :(

**Comment by vhf** [comment]
Ok, la communication node <> python se fera par HTTP, par express + pm2. Zerorpc pose problème avec l'environnement de développement de Django.

Note : 

* Mettre en place le monitoring des process node par Sentry

**Comment by vhf** [comment]
- [ ] #4242 
- [ ] #4199 
- [ ] #4198 
- [ ] #4194 
- [ ] #4193 
- [ ] #4192
- [ ] #3878

**Comment by firm1** [comment]
J'ai une question concernant cette migration. Si j'ai bien compris, après migration, il faudra obligatoirement faire tourner un serveur node en local à coté du serveur local django pour pouvoir bosser en local ?

**Comment by motet-a** [comment]
Techniquement, je ne pense pas que ce soit obligatoire. Comme les rendus HTML sont cachés, on devrait pouvoir naviguer en lecture seule sur le site sans zmarkdown (comme on peut utiliser le site sans ElasticSearch). C’est juste limité.

**Comment by motet-a** [comment]
@firm1 Mais j’ai fait la PR #4430 pour essayer de simplifier drastiquement la mise en route de tout le bazar.

**Comment by firm1** [comment]
> Techniquement, je ne pense pas que ce soit obligatoire.

Je n'ai pas lu le code pour savoir comment ça s'integrera d'où ma question. Il y a quand même les cas de création/edition d'un topic/mp/tuto/article/billet/etc qui necessite le markdown et que l'on utilise souvent en local pendant le dev.

> @firm1 Mais j’ai fait la PR #4430 pour essayer de simplifier drastiquement la mise en route de tout le bazar.

oui j'ai vu passer ça. Mais bon c'est quand même ça à installer en plus. Je me demande si c'est jouable d'utiliser le service node à distance. C'est à dire que le service/api zmarkdown est installé sur notre prod comme un service/api normal et accessible depuis l'exterieur. Et dans le settings on se contente de linker l'url du service zmd (localhost pour ceux qui contribue a zmd et zmarkdown.zestedesavoir.com pour les autres).

**Comment by motet-a** [comment]
Il y a quand même les cas de création/edition d'un topic/mp/tuto/article/billet/etc qui necessite le markdown et que l'on utilise souvent en local pendant le dev.

Oui !

> Je me demande si c'est jouable d'utiliser le service node à distance. C'est à dire que le service/api zmarkdown est installé sur notre prod comme un service/api normal et accessible depuis l'exterieur. Et dans le settings on se contente de linker l'url du service zmd (localhost pour ceux qui contribue a zmd et zmarkdown.zestedesavoir.com pour les autres).

En fait c’est carrément jouable et ça risque vraiment de se faire.

**Comment by pierre-24** [comment]
Gardez pas la solution locale trop loin, ça m'arrive de coder dans le train/l'avion.

**Comment by vhf** [comment]
La solution locale est obligatoire oui, c'est l'autre qui est en bonus. ;)

Il faut pouvoir développer offline, les tests doivent tourner offline, c'est un impératif.

Mais déployer juste le markdown séparément sur la beta et le rendre accessible aux devs qui souhaitent pas installer node localement, c'est largement jouable. Notez quand même que sans node vous pouvez pas builder le front localement, et que si vous pouvez builder le front localement vous pouvez avoir zmarkdown aussi. Le makefile lançant le back lance également zmarkdown, c'est très léger : quand il fait rien zmarkdown prend 0% de CPU, et il redémarre quand il prend plus de 150Mo de RAM (donc il prend max 150Mo de RAM).

<img width="649" alt="screen shot 2017-08-23 at 20 59 13" src="https://user-images.githubusercontent.com/2022803/29633304-23974a84-8846-11e7-889a-5890ef99d22c.png">

**Comment by vhf** [comment]
@sandhose `md.zestedesavoir.com` pointe désormais sur la beta.
